#server:
#  port: 7011
spring:
  application:
    name: service-hi
  cloud:
    config:
      uri: http://localhost:8888
      name: service-hi-7011
      profile: prod
      label: master
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:7022/eureka/


