spring:
  application:
    name: hello-spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7022/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
