spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinfuquan/config-git.git
          search-paths: dev
          username: yinfuquan
          password: q568114162
      label: master
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7022/eureka/

  zipkin:
    base-url: http://localhost:9411