server:
  port: 7012
spring:
  application:
    name: service-hi
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7022/eureka/


  zipkin:
    base-url: http://localhost:9411
hystrix:

  command:

    default:

      execution:

        isolation:

          thread:

            timeoutInMilliseconds: 3000